/** Icono, color y punto de cada tipo de acción de la bitácora. */
export const ACTION_STYLES: Record<string, { icon: string; tone: string; dot: string }> = {
  created: { icon: 'plus-circle', tone: 'text-success-text bg-success-soft', dot: 'success' },
  updated: { icon: 'pencil-square', tone: 'text-primary-active bg-primary-soft', dot: 'primary' },
  deleted: { icon: 'trash3', tone: 'text-danger-text bg-danger-soft', dot: 'danger' },
  downloaded: { icon: 'download', tone: 'text-info-text bg-info-soft', dot: 'info' },
  exported: { icon: 'file-earmark-spreadsheet', tone: 'text-info-text bg-info-soft', dot: 'info' },
  approved: { icon: 'check-circle', tone: 'text-success-text bg-success-soft', dot: 'success' },
  rejected: { icon: 'x-circle', tone: 'text-danger-text bg-danger-soft', dot: 'danger' },
  justified: { icon: 'patch-check', tone: 'text-success-text bg-success-soft', dot: 'success' },
  unjustified: { icon: 'patch-minus', tone: 'text-warning-text bg-warning-soft', dot: 'warning' },
  manual_punch: { icon: 'clock-history', tone: 'text-warning-text bg-warning-soft', dot: 'warning' },
  role_changed: { icon: 'person-gear', tone: 'text-primary-active bg-primary-soft', dot: 'primary' },
  access_changed: { icon: 'key', tone: 'text-warning-text bg-warning-soft', dot: 'warning' },
  permissions_changed: {
    icon: 'shield-lock',
    tone: 'text-warning-text bg-warning-soft',
    dot: 'warning',
  },
  settings_changed: { icon: 'gear', tone: 'text-primary-active bg-primary-soft', dot: 'primary' },
  login: { icon: 'box-arrow-in-right', tone: 'text-muted-text bg-canvas', dot: 'muted' },
  logout: { icon: 'box-arrow-right', tone: 'text-muted-text bg-canvas', dot: 'muted' },
  plan_changed: { icon: 'box-seam', tone: 'text-primary-active bg-primary-soft', dot: 'primary' },
  company_deletion_requested: {
    icon: 'trash3',
    tone: 'text-danger-text bg-danger-soft',
    dot: 'danger',
  },
  payroll_closed: { icon: 'lock', tone: 'text-primary-active bg-primary-soft', dot: 'primary' },
  payroll_reopened: { icon: 'unlock', tone: 'text-warning-text bg-warning-soft', dot: 'warning' },
};

export const DEFAULT_ACTION_STYLE = { icon: 'dot', tone: 'text-muted-text bg-canvas', dot: 'muted' };

/** Nombres legibles de los campos que aparecen en los cambios. */
export const FIELD_LABELS: Record<string, string> = {
  first_name: 'Nombre',
  last_name: 'Apellidos',
  position: 'Puesto',
  email: 'Correo',
  phone: 'Teléfono',
  office_id: 'Oficina',
  shift_id: 'Turno',
  area_id: 'Área',
  status: 'Estado',
  employment_type: 'Tipo de contrato',
  work_mode: 'Modalidad',
  hired_on: 'Fecha de ingreso',
  contract_ends_on: 'Fin de contrato',
  terminated_on: 'Fecha de baja',
  pin_hash: 'PIN',
  badge_token: 'Credencial',
  salary: 'Sueldo',
  salary_period: 'Periodicidad',
  name: 'Nombre',
  latitude: 'Latitud',
  longitude: 'Longitud',
  geofence_radius: 'Radio de geocerca',
  starts_at: 'Entrada',
  ends_at: 'Salida',
  weekdays: 'Días',
  tolerance_minutes: 'Tolerancia',
  absence_after_minutes: 'Falta después de',
  is_active: 'Activo',
  approved_at: 'Autorizado',
  revoked_at: 'Revocado',
  roles: 'Roles',
  permisos: 'Permisos',
  app_access: 'Acceso a la app',
  web_access: 'Acceso web',
  blocked_at: 'Bloqueado',
  employees_can_use_web: 'Empleados en web',
  payroll_enabled: 'Módulo de sueldos',
  bonuses_enabled: 'Módulo de bonos',
  amount: 'Monto',
  conditions: 'Condiciones',
};
